[package]
name = "bewry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
bevy_wry = {path = "../bevy_wry"}
serde = "1.0"
serde_json = "1.0"
